/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    DesktopHeader: typeof import('./components/DesktopHeader.vue')['default']
    LangSwitcher: typeof import('./components/LangSwitcher.vue')['default']
    MapComponent: typeof import('./components/MapComponent.vue')['default']
    MarkerList: typeof import('./components/MarkerList.vue')['default']
    MobileHeader: typeof import('./components/MobileHeader.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
